#!/bin/bash

set -e

if [ ! -d .git ]; then
  echo "Run from top level directory"
  exit 1
fi

LAST_REVISION=
if [ -f $HOME/.gem/.last-jekyll-tagging-revision ]; then
  LAST_REVISION=`cat $HOME/.gem/.last-jekyll-tagging-revision`
fi

# Install jekyll-tagging gem locally for the user
pushd plugins/jekyll-tagging

# Determine whether plugin needs to be installed
CURRENT_REVISION=`git rev-parse HEAD`

if [ "$CURRENT_REVISION" != "$LAST_REVISION" ]; then
  rm -f *.gem
  exec gem build jekyll-tagging.gemspec && gem install --local --user-install --force jekyll *.gem
  `echo $CURRENT_REVISION > $HOME/.gem/.last-jekyll-tagging-revision`
fi

popd
