#!/bin/bash

set -e

if [ ! -d .git ]; then
  echo "Run from top level directory"
  exit 1
fi

# Install jekyll-tagging gem locally for the user
pushd plugins/jekyll-tagging

rm *.gem
gem build jekyll-tagging.gemspec
gem install --local --user-install --force jekyll *.gem

popd
