name: Shaheen Gandhi
url: http://shaheengandhi.com
description: Professional blog for Shaheen Gandhi
markdown: redcarpet
pygments: true
tag_page_layout: default
tag_page_dir: tag
paginate: 4
paginate_path: page/:num
