#!/bin/bash

set -e
set -x

DEPLOY_TO=blog:site/www

if [ ! -d .git ]; then
  echo "Run from top level directory"
  exit 1
fi

TEMP=`mktemp -d`

# Build the site
echo "Building site"
pushd jekyll

pushd _layouts
compass compile
popd

jekyll build -d $TEMP
popd

# Deploy via rsync
rsync -trlvz $TEMP/ $DEPLOY_TO
