name: shaheen gandhi | blog
url: http://shaheengandhi.com
description: programming cocoa and ios
markdown: redcarpet
markdown_ext: markdown,md
pygments: true
tag_page_layout: posts
tag_page_dir: tag
paginate: 4
paginate_path: page/:num
permalink: /:title
