#!/bin/bash
set -e
set -v

unset GIT_DIR
GIT_REPO=$HOME/jekyll.git

# Make a temp directory to perform the work
TEMP=`mktemp -d`
trap "{ rm -rf $TEMP ; exit 255 ; }" EXIT

pushd $TEMP
git clone -b deploy "$GIT_REPO" jekyll
cd jekyll

# Copy receive hook (and deps) back to the bare repository from the clone
cp _tools/git-hooks/post-receive "$GIT_REPO/hooks"

# The checkout hook did not run because it was not installed (the first checkout
# just occurred)
./_tools/git-hooks/post-checkout

# Deploy the site
./_tools/deploy_site

popd

exit 0
