#!/bin/bash
set -e
set -v

. $(git --exec-path)/git-sh-setup

# Make a temp directory to perform the work
TEMP=`mktemp -d`
trap "{ rm -rf $TEMP ; exit 255 ; }" EXIT

pushd $TEMP
echo "cloning from $GIT_DIR"
git clone "$GIT_DIR" jekyll
cd jekyll
git checkout deploy

# The checkout hook did not run because it was not installed (the first checkout
# just occurred)
./_tools/git-hooks/post-checkout

# Copy receive hook (and deps) back to the bare repository from the clone
cp _tools/git-hooks/post-receive "$GIT_DIR/hooks"

# Deploy the site
./_tools/deploy_site

popd

exit 0
