#!/bin/bash
set -e

. $(git --exec-path)/git-sh-setup

# Make a temp directory to perform the work
TEMP=`mktemp -d`
trap "{ rm -rf $TEMP ; exit 255 ; }" EXIT

pushd $TEMP
git clone -l $GIT_DIR jekyll
cd jekyll
git checkout deploy

# The checkout hook will have installed the tagging gem

# Deploy the site
./_tools/deploy_site

popd

exit 0
